{:namespaces
 ({:source-url nil,
   :wiki-url "caribou.api.core-api.html",
   :name "caribou.api.core",
   :doc nil}
  {:source-url nil,
   :wiki-url "caribou.api.halo-api.html",
   :name "caribou.api.halo",
   :doc nil}),
 :vars
 ({:arglists ([slug path-args expr]),
   :name "action",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/action",
   :doc "Define an API action with the given slug and path.",
   :var-type "macro",
   :line 122,
   :file "src/caribou/api/core.clj"}
  {:arglists ([params]),
   :name "ensure-lists-in",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.core-api.html#caribou.api.core/ensure-lists-in",
   :doc "flatten nested params into lists",
   :var-type "function",
   :line 163,
   :file "src/caribou/api/core.clj"}
  {:arglists ([col]),
   :name "ensure-seq",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/ensure-seq",
   :doc
   "if given a map, convert to a seq containing only its values.\notherwise, leave it alone",
   :var-type "function",
   :line 151,
   :file "src/caribou/api/core.clj"}
  {:arglists ([]),
   :name "init",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/init",
   :doc "Initialize the API.",
   :var-type "function",
   :line 306,
   :file "src/caribou/api/core.clj"}
  {:arglists ([bulk]),
   :name "prep-xml",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/prep-xml",
   :doc "Convert everything into XML.",
   :var-type "function",
   :line 92,
   :file "src/caribou/api/core.clj"}
  {:arglists ([bulk]),
   :name "prep-xml-item",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.core-api.html#caribou.api.core/prep-xml-item",
   :doc "Convert something into XML.",
   :var-type "function",
   :line 87,
   :file "src/caribou/api/core.clj"}
  {:arglists ([slug content opts]),
   :name "render",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/render",
   :doc "Prepare all various fields types for output as text.",
   :var-type "function",
   :line 45,
   :file "src/caribou/api/core.clj"}
  {:arglists ([slug content field opts]),
   :name "render-field",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.core-api.html#caribou.api.core/render-field",
   :doc "Render a single content field to text, given the field type.",
   :var-type "function",
   :line 52,
   :file "src/caribou/api/core.clj"}
  {:arglists ([headings bulk]),
   :name "to-csv",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/to-csv",
   :doc "Convert a bunch of data to CSV.",
   :var-type "function",
   :line 80,
   :file "src/caribou/api/core.clj"}
  {:arglists ([bulk key]),
   :name "to-csv-column",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.core-api.html#caribou.api.core/to-csv-column",
   :doc
   "Translate a list into something that can inhabit a single csv row.",
   :var-type "function",
   :line 72,
   :file "src/caribou/api/core.clj"}
  {:arglists ([params]),
   :name "upload",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/upload",
   :doc "Handle a file upload over xdm.",
   :var-type "function",
   :line 176,
   :file "src/caribou/api/core.clj"}
  {:arglists ([callback result]),
   :name "wrap-jsonp",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/caribou.api.core-api.html#caribou.api.core/wrap-jsonp",
   :doc "Turn a callback name and a result into a jsonp response.",
   :var-type "function",
   :line 67,
   :file "src/caribou/api/core.clj"}
  {:arglists ([response meta]),
   :name "wrap-response",
   :namespace "caribou.api.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.core-api.html#caribou.api.core/wrap-response",
   :doc "Form a response from raw stuff.",
   :var-type "function",
   :line 145,
   :file "src/caribou/api/core.clj"}
  {:arglists ([host route-str]),
   :name "halo-endpoint",
   :namespace "caribou.api.halo",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.halo-api.html#caribou.api.halo/halo-endpoint",
   :doc "Define a halo endpoint for the given host and route.",
   :var-type "function",
   :line 9,
   :file "src/caribou/api/halo.clj"}
  {:arglists ([route-str]),
   :name "halo-endpoints",
   :namespace "caribou.api.halo",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.halo-api.html#caribou.api.halo/halo-endpoints",
   :doc "Get all endpoints given by the :halo-hosts configuration.",
   :var-type "function",
   :line 14,
   :file "src/caribou/api/halo.clj"}
  {:arglists ([]),
   :name "halo-headers",
   :namespace "caribou.api.halo",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.halo-api.html#caribou.api.halo/halo-headers",
   :doc "Returns a map of halo required headers.",
   :var-type "function",
   :line 19,
   :file "src/caribou/api/halo.clj"}
  {:arglists ([env]),
   :name "reload-models",
   :namespace "caribou.api.halo",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.halo-api.html#caribou.api.halo/reload-models",
   :doc "Trigger the reloading of every model.",
   :var-type "function",
   :line 32,
   :file "src/caribou/api/halo.clj"}
  {:arglists ([env]),
   :name "reload-routes",
   :namespace "caribou.api.halo",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url
   "/caribou.api.halo-api.html#caribou.api.halo/reload-routes",
   :doc "Trigger the reloading of all page routes.",
   :var-type "function",
   :line 24,
   :file "src/caribou/api/halo.clj"})}
